### ISSUE TITLE
Error running complete cake script

### ISSUE THREAD

**Issue by Tdue21** [cake-build/cake-vscode#102]
When I try to build via the cake script, I get this error: 

```
========================================
Package-Extension
========================================
Executing task: Package-Extension
Executing prepublish script 'npm run vscode:prepublish'...
Error: Command failed: npm run vscode:prepublish
Den angivne sti blev ikke fundet.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cake-vscode@0.1.0 compile: `C:/Users/appveyor/AppData/Roaming/npm/tsc -p ./`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cake-vscode@0.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Thomas\AppData\Roaming\npm-cache\_logs\2018-10-28T13_52_15_751Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cake-vscode@0.1.0 vscode:prepublish: `npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cake-vscode@0.1.0 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Thomas\AppData\Roaming\npm-cache\_logs\2018-10-28T13_52_15_779Z-debug.log

An error occurred when executing task 'Package-Extension'.
```

The references log file has been attached. 
[2018-10-28T13_52_15_779Z-debug.log](https://github.com/cake-build/cake-vscode/files/2522820/2018-10-28T13_52_15_779Z-debug.log)

I am guessing it has something to do with the reference to c:/Users/appveyor, since that user does not exist on my system.

**Comment by Tdue21** [comment]
Seems it is this commit that broke it: 
[46925e087915e13e0741cf4dd6727cd3a9e5a2bf](https://github.com/cake-build/cake-vscode/commit/46925e087915e13e0741cf4dd6727cd3a9e5a2bf)

**Comment by gep13** [comment]
Unfortunately, this was done deliberately...

**Comment by gep13** [comment]
We use AppVeyor as the CI tool for publishing the final release.  It already had tsc installed, but an earlier version, and after installing it globally as part of the build script, the earlier version is still the one that is found when running tsc directly. As such, it was necessary to hard code to the location that we wanted to use.

**Comment by gep13** [comment]
The side effect is that this part of the build is broken locally. If there is another way to do it, I would welcome any ideas you might have.

**Comment by Tdue21** [comment]
Ok, that explains it :)

**Comment by Tdue21** [comment]
How about this: 
"scripts": {
    "vscode:prepublish": "npm run compile",
    "compile": "%APPDATA%/npm/tsc -p ./",
    "watch": "%APPDATA%/npm/tsc -watch -p ./",
    "postinstall": "node ./node_modules/vscode/bin/install",
    "test": "npm run compile && node ./node_modules/vscode/bin/test"
  },

**Comment by gep13** [comment]
@Tdue21 I believe that this has now been addressed.  Thanks for bringing this up.
