### ISSUE TITLE
cake IntelliSense support is too slow  it takes at least 20 seconds to show the response sometimes even longer

### ISSUE THREAD

**Issue by SmGG** [cake-build/cake-vscode#103]
HELP !!!

**Comment by gep13** [comment]
@SmGG In order to best help you with this, you are going to need to provide us with a lot more information than you currently have.

Can you give a full set of steps to reproduce the problem that you are seeing, including the file(s) that you are trying to provide intellisense for.  Also include exactly what versions of Cake, VSCode, etc, that you are using.

**Comment by SmGG** [comment]
VSCode Version:

>Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

CakeVersion: 0.30.00
CakeExtensionVersion: 0.11.4

**Comment by SmGG** [comment]
Do I have to provide the files? @gep13

**Comment by gep13** [comment]
@SmGG if you can, that would help.  Or, for instance, do you see the same problem when using something the example repository?

At the end of the day, we need a complete set of steps to reproduce your problem, or we are not going to be able to help.

**Comment by SmGG** [comment]
I'm a beginner, it's my first project using cake. I can tell the code is quite a mess, and the main file build.cake got nearly 600 lines, and it loads four other cake files, got three addins 

> #addin nuget:?package=Cake.Svn&version=0.5.0
#addin nuget:?package=Cake.IIS&version=0.4.1
#addin nuget:?package=Commando.UI&version=1.3.0

and 8 using,

>// Usings
using System.IO;
using System.Text.RegularExpressions;
using Commando.Colors;
using Commando.Colors.Textwriter;
using Commando.Pretty;
using Commando.Progress;
using Commando.Prompt;
using Commando.Table;

does it help?

**Comment by gep13** [comment]
@SmGG sorry, but no.  I can't reproduce that problem with the information that you have provided.  If you can provide a complete sample build script and project that exhibits the problem for you, then we would be able to start digging into this further, assuming we can reproduce the problem with the project you provide.

**Comment by SmGG** [comment]
@SmGG  could I just provide you the cake file? the project file is private
[cakefiles.zip](https://github.com/cake-build/cake-vscode/files/2556743/cakefiles.zip)

**Comment by SmGG** [comment]
@gep13  I think I have reproduced the problem using the files I provide you. can you reproduce the problem?

**Comment by SmGG** [comment]
@gep13 

1. Download the zip
2. Check out the cake example from git@github.com:marcosnz/Cake-Example.git
3. Cover the file by using the cake files in the downloaded zip file
4. Open with VSCode install Intellisense support for cake files
5. Run a task default to install cake
6. Restart VSCode to make Intellisense support take effect 
7. Try to write something, problem reproduced

**Comment by SmGG** [comment]
now, cake just doesn't work anymore, not just slow, What Happened!!!!
>[warn]: OmniSharp.Cake.CakeProjectSystem
        Could not initialize Cake script service. Aborting.

Please help me @gep13

**Comment by SmGG** [comment]
oh, sorry I forgot to install cake.backery yesterday, my fault. but it still very slow, @gep13

**Comment by SmGG** [comment]
It seems like this problem is no longer exists in my project, it's all good for me now, the Intellisense support is now fast and smooth. 
>Cake version 0.35.0
Cake.Bakery version 0.4.1
Cake Extention version 0.12.0
dotnet version 2.2.100

thanks for your patient, and sorry for bothering you, 😂  @gep13
