### ISSUE TITLE
Dotnet global tool support

### ISSUE THREAD

**Issue by n-sidorov** [cake-build/cake-vscode#104]
Cake v0.30 introduced an ability to run scripts via `dotnet cake` (https://cakebuild.net/blog/#global-tool) without the need of `build.ps1`.

Cake VS Code extension currently has cool auto-discover functionality but it works only with `build.ps`.

Is there are any plans to support global dotnet tool in this scenario?

**Comment by DanFTRX** [comment]
This would be nice.  I can no longer use this extension because FIPS compliance prevents using the build.ps1 bootstrapper.

**Comment by pascalberger** [comment]
@gep13 Is this a duplicate of #376?

**Comment by gep13** [comment]
@pascalberger yes, I think there are several overlapping issues here.  Let's go ahead and close this one out, in favour of the others that are actively being worked on.
