### ISSUE TITLE
Cake tasks are failing to be recognized

### ISSUE THREAD

**Issue by joelday** [cake-build/cake-vscode#107]
This started as of the most recent Insiders build:

```
Error: The cake task detection didn't contribute a task for the following configuration:
{
    "label": "buildExtension",
    "type": "cake",
    "script": "build-extension",
    "problemMatcher": [
        "$tsc",
        "$msCompile"
    ]
}
The task will be ignored.
```

Version: 1.31.0-insider (user setup)
Commit: ece3a90fb58986570d8afdfb16530c4dd8c743af
Date: 2018-12-14T06:19:42.976Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Thanks!

**Comment by Duracell1989** [comment]
It appears to be fixed in #https://github.com/Microsoft/vscode/issues/67990. Please try to use the latest version of VSCode (1.31.1)

**Comment by gep13** [comment]
@Duracell1989 thank you for confirming.

@joelday going to go ahead and close this, but let us know if you are still facing problems.
