### ISSUE TITLE
Adopt extension for no reload on install 

### ISSUE THREAD

**Issue by sandy081** [cake-build/cake-vscode#133]
Hi, I am a developer from VS Code and in the last release `1.31`, we added a new feature - no reload is required on installing an extension - https://code.visualstudio.com/updates/v1_31#_no-reload-on-install

But there are some exceptions to it as mentioned in the doc. If the extension is contributing to external contribution points, then the extension requires reload after installing. Hence, we added a new listener API for the owners of the external contribution point to listen to extension addition/removal and can update its state - https://code.visualstudio.com/updates/v1_31#_extensions-change-event.

Our plan is to give extensions one milestone/month for adopting to the above API and make the other extensions consuming their contribution points ready for no reload. It means that from next release, above exception will be removed and all extensions are added to VS Code window immediately after installation and no reload is shown.

We scanned the extensions in the marketplace and found out that this extension uses an external contribution point `outputChannels` and requires reload on install. Since we cannot find out which extension owns this contribution point filing an issue here and please forward it to the extension that owns this contribution point to adopt.

Thanks

**Comment by gep13** [comment]
@sandy081 thank you for reaching out!

It looks like it is indeed our extension that is making use of this:

https://github.com/cake-build/cake-vscode/blob/dbe1413728e5d88ef6a9593def2f6ac8a2047d6d/package.json#L98-L100

Are you able to provide any additional details about exactly what needs to be done within our extension to adhere to the new guidelines?  Do you have any examples?

**Comment by sandy081** [comment]
@gep13 If you define a contribution point for other extensions to use then you might be providing some functionality that others can use by contributing to your contribution point. 

For example, VS Code has out of the box many contribution points like `configurations`. It means if an extension contributes to this contribution point then VS Code allows users to customise contributed configurations through Settings.

In such a case, you should be reading your contribution point in `package.json`s of all extensions using the API `vscode.extensions.all` and update your functionality/state. You are also supposed to update your state when there is a change in extensions (added/removed) by listening to `vscode.extensions.onDidChange` event. This change event was added in last release which is needed for No Reload on Install feature.

In your case, please contact the extension that owns `outputChannels` contribution point and ask them to adopt to the new change event mentioned above. If you own this contribution point and not meant to be extended by others, I would suggest to remove it from the `package.json` and hard code it in the code.

**Comment by gep13** [comment]
@sandy081 we believe we have made the necessary changes, and pushed out a new version of the extension.

Can you please confirm that we have completed the necessary work?

Thanks

**Comment by sandy081** [comment]
I do not think I am the right person to verify the internal behaviour of this extension. Please check if your extension is working properly after getting installed (without window reload).

**Comment by gep13** [comment]
@sandy081 bottom line is, the extra additions in the package.json were not something that any of the Cake Team knew about. They were added as part of a PR that we received, and we were not intentionally extending the functionality.

This addition has been removed, as per the associated commit, and the extension continues to work as expected.  Is this the only change that you expected?

When I upgraded to the new 0.12.0 version of the extension, I was still prompted to reload after it completed. Would you have expected this?

Thanks

**Comment by sandy081** [comment]
Yeah, update prompts reload because the extension is running. Please check during fresh install.

**Comment by gep13** [comment]
>@sandy081 said...
Yeah, update prompts reload because the extension is running. Please check during fresh install.

Thanks.  I can confirm that a fresh installation of the extension did not bring up a reload prompt.

Thanks again for your help and support with that.
