### ISSUE TITLE
Debug Task fails on Windows

### ISSUE THREAD

**Issue by odalet** [cake-build/cake-vscode#222]
Relates to issue #80

I just downloaded cake and the vscode extension, had a look at the video and tried to debug a task (in the sample project) by directly clicking the 'debug task' codelens link.

When I do so, I get insulted by cake in the debug output saying:

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```
then the process exits.

I understand cake is unhappy because it is probably trying to debug using NEtfx instead of .NET Core (such a situation may never happen on Mac/Linux boxes).

What's weird s that debugging the whole script (by going to the debug tab and creating the default 'cake debug configuration') just works!

I had a quick look at the extension code and noticed that the 'debug task command' was looking for debug settings when installed (see `_getCodeLensConfig` in `cakeMain.ts`). If these settings do not exist (as is the case for me) I suppose the debugging experience reverts to what mqkes more sense on a Windows machine, hence with full .NET support... 
Wouldn't it be possible for the 'DebugTask' command to use the same/similar configuration as the global 'Debug' command? Or at least to force the 'debug type' to 'coreclr' in `cakeDebugTask.ts`? 

Hope I make sense here. And anyway, this extension as well as cake itself seem a really great piece of... code!

**Comment by odalet** [comment]
Replying to myself:

The problem seems more complex than I thought. I forked the extension, debugged through it and could not see what's going wrong when debugging a task (the 'coreclr' type is correctly set when creating the debug configuration). Maybe this is related to my machine's specific setup...

In conclusion, the bug still exists for me, but I have no clue how it could be fixed!

**Comment by odalet** [comment]
OK, end of the story: I had completely misinterpreted the message from vsdbg...
I still have a problem: I can use the debug codelens successfully only when debugging the omnisharp extension. When running the officially installed omnisharp extension, vsdbg seems not to see any breakpoint. 

Anyway, I think the issue is on the omnisharp side (or my machine), not here. Closing this issue.

**Comment by lstefano71** [comment]
Sorry to comment on a closed issue. Did you ever get to the bottom of this? I am having exactly the same issue. Thank you in advance.

**Comment by odalet** [comment]
Unfortunately I didn't. I too experienced again these issues, but I'm not able to consistently reproduce them. And... I'm not using cake any more at the moment. 
All this explains why I closed the issue. I may come back to it if I ever play again with cake.
