### ISSUE TITLE
Keyword highlighting includes left parenthesis

### ISSUE THREAD

**Issue by kolletzki** [cake-build/cake-vscode#25]
The keyword highlighting also highlights the left parenthesis after the keyword:

![Screenshot](https://i.imgur.com/KiFG56G.png)

Note: I open this issue since #22 seems to be stuck because no proper issue exists.

**Comment by agc93** [comment]
Awesome thanks for the reminder @kolletzki we'll get this moving :+1:

**Comment by Roemer** [comment]
When will there be a release with this fix?
