### ISSUE TITLE
Support ability to setup/install debugging dependencies

### ISSUE THREAD

**Issue by Redth** [cake-build/cake-vscode#27]
Currently, to setup dotnet core debugging in a folder for cake script, it's a little bit more work than I'd like :)

I'm proposing that a command be created for this vs-code extension that does a couple things:

1. Adds a `.vscode/launch.json` file with the default template, which assumes build.cake should be run.
2. Cake.CoreCLR should be installed to the `./tools/` dir (where the launch.json template expects it) when this command is run.

Not really picky or sure what the command should be, but maybe something like `Cake: Install Debugging`

**Comment by alexreg** [comment]
I agree, this would be really nice! It doesn't have to necessarily be for .NET Core. (Ordinary .NET/Mono would be just fine.)

@Redth Do you have a template you use for this right now?

**Comment by gep13** [comment]
@Redth I like this idea, but I am hoping that this "might" not be required.  With the ability to autodetect and add Tasks into the running VSCode, I am hoping to be able to add a debug task, which will launch the debugger.  If this doesn't work out, then the fallback will be your suggestion.

**Comment by Redth** [comment]
Automatically would be even better of course :)

**Comment by gep13** [comment]
@Redth what are your thoughts on the following?

![setup debugging1](https://user-images.githubusercontent.com/1271146/28339081-d7475854-6c02-11e7-81ca-18286f3a8829.gif)

This allows adding the launch task in one of two ways.

Firstly, if you don't have a launch.json file already, pressing F5 brings up a list of available options, of which Cake is now one of them.  Clicking on this creating the launch.json file, and populates with required information.

Secondly, if you already have a launch.json file, you can get intellisense for adding the same information.

Once set up, saving the launch.json file and pressing F5 starts the debugging session as normal.

Currently, this doesn't handle downloading of the Cake.CoreCLR package, but it is a step in the right direction 😄

**Comment by gep13** [comment]
@Redth do you still think another registered command to download the Cake.CoreCLR package is the correct way to go?  Or should it be left up to the end user to run the bootstrapper at least once to get the packages.config file, then update it to include the Cake.CoreCLR package?

@cake-build/cake-team what are your thoughts on this?

**Comment by Redth** [comment]
i definitely think that's helpful.... i want to look at where i left off investigating getting mono to debug cake.exe working too, which might change how you would want to set up launch.json in this case.  I think ultimately using dotnet core is the best path, but i think we're a ways away from that still.

I'm torn on a step to download the package.... I guess there's no way to hook that into this task?

**Comment by gep13** [comment]
@Redth technically, if you go down the route of having no launch.json file, then choosing Cake from the first drop down list, I could do some additional work in there to download the Cake.CoreCLR package into the tools folder.  However, this wouldn't work for when you are using the intellisense snippet on an existing launch.json file.

From a consistency point of view, I think I would prefer a separate command that downloads and extracts the package, which could be used for both routes.

Thoughts?

**Comment by Redth** [comment]
Yeah i think you're right...  a command wouldn't hurt, maybe keeping it in a generic name like "Install Cake debug dependencies" or something?

**Comment by gep13** [comment]
>@Redth said...
 which might change how you would want to set up launch.json in this case.

If you get this up and running, then I can certainly add other options into either the snippets or the initial configurations to provide the necessary information to debug in that manner.
