### ISSUE TITLE
Add ProblemMatcher to new TaskProvider

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-vscode#32]
To help with identifying issues with the build.

This suggestion was made by @egamma

https://twitter.com/ErichGamma/status/888732494002106370

**Comment by egamma** [comment]
@gep13 there are two scenarios to consider.

- when a task provider is for a build tool with well known error message formats, then a task provider can associate one or more problem matchers with a created task. This is done by the haxe task provider https://github.com/vshaxe/vshaxe/blob/master/src/vshaxe/tasks/HxmlTaskProvider.hx#L22
- if the build is more open ended and allows to use many different tools that are using different formats for error messages, then your extension wants to contribute problem matchers for the most common error formats and defer to the user to associate problem matchers in the task.json for a particular build.
