### ISSUE TITLE
Cannot activate the 'Cake' extension because it depends on an unknown 'ms-vscode.csharp' extension

### ISSUE THREAD

**Issue by jrmnl** [cake-build/cake-vscode#329]
Hi,
I can't use extension because of it depends on "ms-vscode.csharp" instead of "ms-dotnettools.csharp". omnisharp-vscode updated its publisher name in 1.21.13 version.
There is pull request with possible fix - https://github.com/cake-build/cake-vscode/pull/323

Steps to reproduce:
1. install vs code
2. install cake extensions
3. open cake file

Result: 
error message - "Cannot activate the 'Cake' extension because it depends on an unknown 'ms-vscode.csharp' extension ."

**Comment by Mezzenine** [comment]
I have the same issue.

**Comment by tc4rdpp** [comment]
I have the same issue as well.

**Comment by gep13** [comment]
@jrmnl @Mezzenine @tc4rdpp a new version, 0.13.0, of the Cake extension has just been released, and it appears to fix this problem.  Please let us know if you see any other problems.
