### ISSUE TITLE
Add "Install a build file" Command

### ISSUE THREAD

**Issue by anrichter** [cake-build/cake-vscode#37]
Hi,

when i start with cake in a project i can install a bootstrapper and a config file throgh this plugin.
Thats nice but not sufficent for me.

It would be nice, when i can install a build.cake script file also. Preferably with a working skeleton like the one from the [Setting up a new project](http://cakebuild.net/docs/tutorials/setting-up-a-new-project) page.

So i can open Code in a project without cake and can install the bootstrapper, config and a running build scripts.

Thanks & Greetings,
Andreas

**Comment by gep13** [comment]
@anrichter I actually had the same thought 😄 

I created this issue yesterday https://github.com/cake-build/cake-vscode/issues/33 which has been implemented locally.  This means that there is a snippet available which you can run after you add a build.cake file to the project, which will stub out a complete sample script.

Would this satisfy this issue?

**Comment by anrichter** [comment]
He @gep13 

It's not exactly the same. As i understand, with your Snipped i have to create the build.cake file by myself and than run the snippet inside this file.

What i would like to see is a command in VS Code which creates the build.cake file and fill it with the content of your snippet.

So i have to run 3 VS Code commands and have a working skeleton for cake build in a fresh project.

**Comment by gep13** [comment]
@anrichter I have spoken with the team, and we think that this would make sense, yes.

In addition to this new command for adding a build script, we are thinking that an aggregate command to add all the necessary files would be useful.  So bascially, the Visual Studio Code equivalent of the wizard that yeoman creates:

http://cakebuild.net/blog/2016/09/cake-for-yeoman

**Comment by anrichter** [comment]
@gep13 That's sounds good :)

The Aggregate Command makes sense to me too.
I also thought about it, as is wrote the last comment ;)

**Comment by gep13** [comment]
@anrichter thank you for the suggestion.  This will be in the next release 😄
