### ISSUE TITLE
Debug should use Cake.Tool instead of Cake.CoreCLR

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake-vscode#376]
When installing debug dependencies. Install `Cake.Tool` as global tool instead of `Cake.CoreCLR` locally.
https://github.com/cake-build/cake-vscode/blob/df630c4e1681b132bf5c3035c053b73a50877fb0/src/debug/cakeDebug.ts

We should also update `package.config` to use `Cake.Tool`:
https://github.com/cake-build/cake-vscode/blob/372b91f34fb5383ebddb37aa29f6237109638374/package.json

**Comment by gep13** [comment]
Final launch.json used during stream on 29th June 2020:

```
        {
            "name": "Cake: Debug Script (CoreCLR)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet-cake.exe",
            "args": [
                "${workspaceRoot}/build.cake",
                "--debug",
                "--verbosity=diagnostic"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": true,
            "externalConsole": false,
            "justMyCode": false,
            "symbolOptions": {
                "searchNuGetOrgSymbolServer": true
            }
        }
```

**Comment by gep13** [comment]
@mholo65 @devlead using the above example, this:

```
"program": "dotnet-cake.exe",
```

Would couple it directly to Windows, right?

What is the correct thing to put in here, so that it would work on both Windows and other operating systems?

**Comment by gep13** [comment]
Would this work:

```
{
            "name": "Cake: Debug Script (Tool)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "cake",
                "${workspaceRoot}/build.cake",
                "--debug",
                "--verbosity=diagnostic"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": true,
            "externalConsole": false,
            "justMyCode": false,
            "symbolOptions": {
                "searchNuGetOrgSymbolServer": true
            }
          }
```

**Comment by devlead** [comment]
In theory, it should and if it does then it would also mean we supported local tools that don't generate the executable stubs.

**Comment by gep13** [comment]
@devlead I tried this on the stream last night, and it didn't work, it only stepped into the debugger when using `dotnet-cake.exe` or `dotnet-cake`.  So unless there is something else that needs to be done to get it to work, i.e. passing arguments differently, then we won't be able to go down this route.

**Comment by mholo65** [comment]
Problem is that `dotnet` is implicit when using type CoreCLR. So now debugger will launch with `dotnet dotnet cake <args>` and that doesn't work. I don't think `cake` as executable will work either, since that can't be find on path ☹️

**Comment by devlead** [comment]
So this starts script and debugging for me...
```json
        {
            "name": "Cake: Debug Script (Tool)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "dotnet-cake",
                "${workspaceRoot}/build.cake",
                "--debug",
                "--verbosity=diagnostic"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": true,
            "externalConsole": false,
            "justMyCode": false,
            "symbolOptions": {
                "searchNuGetOrgSymbolServer": true
            }
        },
```

Issue is that seems to start a child process so it gets stuck at
```
Attach debugger to process 61752 to continue...
```

**Comment by devlead** [comment]
Node has `autoAttachChildProcesses`, but .NET doesn't seem to have.

**Comment by devlead** [comment]
Above is short for
```json
 {
            "name": "Cake: Debug Script (Tool)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "tool",
                "run",
                "dotnet-cake",
                "--",
                "${workspaceRoot}/build.cake",
                "--debug",
                "--verbosity=diagnostic"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": true,
            "externalConsole": false,
            "justMyCode": false,

            "symbolOptions": {
                "searchNuGetOrgSymbolServer": true
            }
        }
```
But still launches a child process.

**Comment by gep13** [comment]
I haven't tried it, but I "think" we should be able to do:

```
        {
            "name": "Cake: Debug Script (Tool)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet-cake",
            "windows": {
                "program": "dotnet-cake.exe"
            }
            "args": [
                "${workspaceRoot}/build.cake",
                "--debug",
                "--verbosity=diagnostic"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": true,
            "externalConsole": false,
            "justMyCode": false,
            "symbolOptions": {
                "searchNuGetOrgSymbolServer": true
            }
        }
```

This is based on this:

https://code.visualstudio.com/docs/editor/debugging#_platformspecific-properties

**Comment by devlead** [comment]
Yes, that would work, requirement then that the Cake tool is installed globally though, won't work for tool manifest installs.

Maybe we could create something in the extension for launch and attach to process if `Attach debugger to process xxxxx to continue...` appears in stdout.

i.e. this
`dotnet tool run dotnet-cake -- build.cake --debug --verbosity=diagnostic`

works with attach
![image](https://user-images.githubusercontent.com/1647294/97286093-5f8ec680-1843-11eb-8644-7256bd54f56a.png)

configuration used:
```json
 {
            "name": "Cake: Debug Script (Tool) Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "justMyCode": false,
            "symbolOptions": {
                "searchNuGetOrgSymbolServer": true
            }
        }
```

**Comment by gep13** [comment]
>@devlead said...
Yes, that would work, requirement then that the Cake tool is installed globally though, won't work for tool manifest installs.

I guess I am confused a little bit about this.

Am I right in saying that shim files are still created when installed via tool manifest?  If so, it would be a case of getting the launch.json to also look in there, right?

We can certainly add an attach into the launch.json as part of the extension.

**Comment by devlead** [comment]
shim files aren't created when installed using manifest, and that's the issue.

**Comment by devlead** [comment]
What we would need would be something like the `serverReadyAction` but for child processes or .NET supported auto attach child processes like node.

I.e. this will launch a browser with the process id, not very helpful but there's a way to launch a debugger in similar way that would sort things.

```json
{
            "name": "Cake: Debug Script (Tool)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "tool",
                "run",
                "dotnet-cake",
                "--",
                "${workspaceRoot}/build.cake",
                "--debug",
                "--verbosity=diagnostic"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": true,
            "externalConsole": false,
            "justMyCode": false,

            "symbolOptions": {
                "searchNuGetOrgSymbolServer": true
            },
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bAttach debugger to process\\s([0-9]+)\\b to continue\\.\\.\\.",
                "uriFormat": "http://localhost:%s"
            }
        }
```

**Comment by gep13** [comment]
Debugging the spawning of child processes is being tracked in this issue: https://github.com/dotnet/runtime/issues/43924
