### ISSUE TITLE
cake.taskRunner.launchCommand still defaults to using a bootstrapper

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake-vscode#461]
`cake.taskRunner.launchCommand` (correctly) defaults to the .NET Tool (i.e. equal to `{ "default": "~/.dotnet/tools/dotnet-cake", "win32": "dotnet-cake.exe" }` 

`cake.taskRunner.launchCommand` still (wrongly) defaults to `{"default": "./build.sh", "win32": "powershell -ExecutionPolicy ByPass -File build.ps1"}`

**Comment by nils-a** [comment]
@gep13 for `cake.taskRunner.launchCommand` the default of `dotnet cake` should suffice, right? No platform specifics needed here.

**Comment by gep13** [comment]
@nils-a based on what we discussed on the stream last night, we want everything to default to a globally installed version of the Cake .NET Global tool, so this would equate to `dotnet-cake` or `dotnet-cake.exe`.  If we switch to using `dotnet cake` which would a locally installed version of the tool, then the run task command will work, but the debug task command won't.
