### ISSUE TITLE
Extension won't build on macOS

### ISSUE THREAD

**Issue by Redth** [cake-build/cake-vscode#47]
There's a few issues in the build script causing things to fail to build on macOS:

- [ ] Version info is being pulled from non-existent source code: https://github.com/cake-build/cake-vscode/blob/develop/build/version.cake#L22
The usual code path that runs on windows is being explicitly skipped and so another code path which is no longer valid is run instead.

- [ ] VscePackage command cannot locate vsce that was installed, we need to add ToolPath here on macOS: https://github.com/cake-build/cake-vscode/blob/develop/build.cake#L114
I'm not sure if this is appropriate for linux, but on macOS simply setting `ToolPath = "/usr/local/bin/vsce"` is a workable solution.

- [ ] For some reason `Clean` is being run AFTER `Install-Vsce` if I just invoke the Default target.  I'm not sure if this is something weird happening with the Mono Scripting engine and can be ignored once Roslyn support is released or what.

**Comment by gep13** [comment]
@Redth for the second problem, I think the problem here actually lies with the Cake.VsCode addin.  I think I need to provide alternative tool paths:

https://github.com/cake-contrib/Cake.VsCode/blob/develop/Source/Cake.VsCode/VsceTool.cs#L57

**Comment by Redth** [comment]
@gep13 alternative tool paths and also add just `vsce` as a tool name (instead of only `vsce.cmd`)

**Comment by gep13** [comment]
@Redth if/when you have a minute, can you take a look at this again?

The latest code on the develop branch now successfully builds on Travis for both Linux and OSX.  Could you test it out locally as well?

And if you are happy, we can close this out.

**Comment by Redth** [comment]
@gep13 works perfectly here, thanks!

**Comment by gep13** [comment]
@Redth sweet! Thanks for checking!
