### ISSUE TITLE
When running "Cake: Install to workspace", installing debug-dependencies should ask

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake-vscode#470]
which runner should be installed.

Currently though, the runner for .NET Framework is always installed.

There's also a *TODO* in the codebase for exactly this: https://github.com/cake-build/cake-vscode/blob/240270bcbbf408570389f218080a681c81eb41ed/src/install/actions/installCake.ts#L73

**Comment by gep13** [comment]
Thanks for adding this, I was going to submit the issue today as I noticed this when doing the other work.

Is this something you are working on?

**Comment by nils-a** [comment]
No, currently not working on it.

**Comment by gep13** [comment]
@nils-a that's fine, just wanted to check before I started working on it.  Going to try to get this done today.
