### ISSUE TITLE
update-checks for Cake Tool only works with .NET 5 installed 

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake-vscode#473]
as discussed on stream, currently the update check (from #460 ) is done using `dotnet tool search cake.tool` . `dotnet tool search` is only available on .NET 5.

While the code is not visibly failing, no version check is performed as long as .NET 5 is not available.

An alternative to checking existing versions using `dotnet` could be accessing either
`https://azuresearch-usnc.nuget.org/autocomplete?id=cake.tool&prerelease=false` or `https://azuresearch-usnc.nuget.org/query?q=Cake.Tool&prerelease=false`

**Comment by gep13** [comment]
@nils-a I am not going to assign this to the milestone, since this is related to #460, which is already part of the milestone.
