### ISSUE TITLE
Error downloading bootstrappers: Failed download configuration: Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake-vscode#477]
I've just upgraded to v1.0.0 and tried to run the task "Cake: Install to workspace" (selecting all the default options) on an empty folder.

![image](https://user-images.githubusercontent.com/177608/100808127-f41fb200-3409-11eb-9efb-4c8485addd0f.png)

I think I saw @gep13 having the same error yesterday during the stream and I had the impression it was related to caching of config settings?

Reporting just for documentation purposes as I think this might happen to more users.

Configuration:

![image](https://user-images.githubusercontent.com/177608/100808139-f8e46600-3409-11eb-8240-6a3364819528.png)

---

##### OmniSharp log

```
Starting OmniSharp server at 12/1/2020, 7:25:34 PM
    Target: c:\augustoproiete\test-cake-intellisense

OmniSharp server started.
    Path: c:\Users\augustoproiete\.vscode\extensions\ms-dotnettools.csharp-1.23.6\.omnisharp\1.37.5-beta.23\OmniSharp.exe
    PID: 33408

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.8.30717.126 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\augustoproiete\.vscode\extensions\ms-dotnettools.csharp-1.23.6\.omnisharp\1.37.5-beta.23\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.8.30717.126 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\augustoproiete\test-cake-intellisense'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Found 1 Cake files.
[warn]: OmniSharp.Cake.CakeProjectSystem
        Could not initialize Cake script service. Aborting.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\augustoproiete\test-cake-intellisense'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\augustoproiete\test-cake-intellisense'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\augustoproiete\test-cake-intellisense' on host 6764.
```

#### Version info

- VSCode
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

- Cake VSCode
Version: 1.0.0

**Comment by gep13** [comment]
@augustoproiete thank you for raising this.  This is indeed the same error that I had during my stream on Monday night.  For me, this was an intermittent problem.  Running it again, everything would work.

Can you confirm if this is also the case for you, or is it happening every time?

**Comment by augustoproiete** [comment]
Closing this as cannot reproduce anymore. Exercised adding bootstrappers (.ps1 & .sh) multiple times, repeating tests after uninstalling and installing the extension again a few times... And don't see this error anymore, and bootstrappers are downloaded.

My guess is that either it was a one-time issue when migration from the 0.x extension to 1.0, or it's a temporary connection issue to https://cakebuild.net/download/bootstrapper/dotnet-framework/bash sometimes.
