### ISSUE TITLE
addin directive stops debugger working

### ISSUE THREAD

**Issue by jsacapdev** [cake-build/cake-vscode#48]
## Environment data
Windows 10

Extension version:
0.8.0

## Steps to reproduce

1. create new directory
2. add build.cake:

```
#addin nuget:?package=Cake.Git

var target = Argument("target", "Default");

Task("Default")
  .Does(() =>
{
  var greeting = "Hello World!";
  Information(greeting);
});

RunTarget(target);
```

3. add build.ps1 bootstrap (Cake: Install a Bootstrapper)
4. add cake.config:

```
; This is the default configuration file for Cake.
; This file was downloaded from https://github.com/cake-build/resources

[Nuget]
Source=https://packages.nuget.org/api/v2

[Roslyn]
NuGetSource=https://packages.nuget.org/api/v2

[Paths]
Tools=./tools
Addins=./tools/Addins
Modules=./tools/Modules
```

5. Download Debug dependencies and setup launch.config:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Cake: Debug Script",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceRoot}/tools/Cake.CoreCLR/Cake.dll",
            "args": [
                "${workspaceRoot}/build.cake",
                "--debug",
                "--verbosity=diagnostic"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": true,
            "externalConsole": false
        }
    ]
}
```

6. F5 to debug

## Expected  behavior

Breakpoint in Default is hit

## Actual behavior

Error: System.InvalidOperationException: Something went wrong when parsing framework.
   at Cake.NuGet.V3.NuGetV3ContentResolver.ParseFromDirectoryPath(NuGetFramework current, DirectoryPath path)
   at Cake.NuGet.V3.NuGetV3ContentResolver.GetAddinAssemblies(DirectoryPath path)
   at Cake.NuGet.NuGetPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path)
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(ScriptAnalyzerResult analyzerResult, DirectoryPath installPath)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.DebugCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
The program '[2652] Cake.dll' has exited with code 1 (0x1).

## Additional Information:

Remove ```#addin nuget:?package=Cake.Git``` and it works.

If ```#addin nuget:?package=Cake.Git``` is included, Run Tasks -> Run Default works.

**Comment by gep13** [comment]
@jsacapdev in order for the debugger in VSCode to work, all addin's that are used within the script need to support .NET Core, as it is the .NET Core debugger that is used within it.  Cake.Git is currently only compiled for full framework.

Another option, which is almost ready, would be to use the Mono Debugger in VSCode.  This should allow you to debug correctly.

**Comment by jsacapdev** [comment]
Thanks.

For my own understanding, is that a Mono debugger for Cake? So, something like:

"program": "${workspaceRoot}/tools/Cake.Mono/Cake.dll"

**Comment by patriksvensson** [comment]
No, the standard Mono debugger for VSCode by Microsoft.

**Comment by mholo65** [comment]
But debugging with mono requires Cake 0.22, which is not yet shipped
