### ISSUE TITLE
#load directive syntax highlighting broken with slash characters

### ISSUE THREAD

**Issue by tritao** [cake-build/cake-vscode#51]
When encountering a directive like `#load "foo/bar.cake"` then highlighting is broken and stays white instead of blue like other directives.

**Comment by gep13** [comment]
Based on the fact that we are planning on removing the custom syntax highlighting (as explained in this issue: https://github.com/cake-build/cake-vscode/issues/52) I am not sure if there is going to be anything that we can do if this happens with the out of the box syntax highlighting offered by C#.

I am going to go ahead and close this issue.  Please feel free to respond back if there is anything else that you want to add.
