### ISSUE TITLE
Read values from cake.config file

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-vscode#57]
As discussed in this PR:

https://github.com/cake-build/cake-vscode/pull/56#discussion_r146886857

Rather than hard-coding the string

**Comment by gep13** [comment]
@nksfrank were you in a position to push the work that you had done on this as a PR?  Thanks again for all your help on Friday!

**Comment by nksfrank** [comment]
@gep13 here's what I managed to pull together last at Knowabunga. The code needs some spring cleaning. And, the ini and @types/ini packages need to be added. I don't know why it didn't seem to stick in side the package.json file after a build, so I didn't push the package.json file with this pr.
Thank you for joining us and for a great Knowabunga

**Comment by gep13** [comment]
@nksfrank thank you for putting this together, I really appreciate it.  I will have a look at the code 😄

**Comment by sean-rose** [comment]
@gep13 This issue is affecting me, but v0.11.0 with this fix hasn't been released yet (latest version available is v0.10.1 released in November).  Any idea when v0.11.0 might be released to the Visual Studio marketplace?
