### ISSUE TITLE
Once Cake.Bakery is installed, restart Omnisharp server

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-vscode#65]
Once the Cake.Bakery package is downloaded from the install command, we should restart the Omnisharp server so that things can start up.

This will prevent the need to close/open Visual Studio Code when setting up for the first time.

Have a read of this twitter discussion:

https://twitter.com/gep13/status/928349645302099968

**Comment by iHaveBecomeDeath** [comment]
commands.executeCommand('o.restart');        
does not seem to do the trick. Neither does command palette -> restart omnisharp server.

Restarting VS Code does help though!

**Comment by gep13** [comment]
@iHaveBecomeDeath I have added in the logic that you suggested, and going to take this for a spin in an actual release, to see what happens, YOLO! 😄
