### ISSUE TITLE
No intellisense support

### ISSUE THREAD

**Issue by lonix1** [cake-build/cake-vscode#693]
I followed the [instructions](https://cakebuild.net/docs/integrations/editors/vscode/intellisense) on the website, but I don't get full cake support.

environment
- linux ubuntu 20.04
- dotnet 6.0.302 (latest)
- vscode 1.70.0 (latest)
- c# extension 1.25.0 (latest)
- cake extension 2.0.0 (latest)

repro
- dotnet new console --output /tmp/cake
- code /tmp/cake
- install c# extension, cake extension
- reload
- command: "Cake: install to workspace", accept all defaults
- command: "Cake: update intellisense support"
- reload
- open `build.cake`

result:
- no intellisense
- red error squiggles under all cake functions, e.g. `Setup`, `Teardown`, `Task`, etc. - shows "The name 'Teardown' does not exist in the current context"
- works: tasks in command palette
- works: codelens items
- works: snippets

logs:
- no errors in `Cake Workspace`
- no errors in `OmniSharp Log` and no messages related to cake, but it does show this when I open `build.cake`:
    ````
    [warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
            No document found. File: /tmp/cake/build.cake.
    [info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
            Could not find document for file /tmp/cake/build.cake
    ````

notes:
- I ran `dotnet tool install --global cake.tool`
- I also uninstalled and reinstalled all the extensions, without success
- I didn't change any of the extension's options in `.vscode/settings.json`
- I also tried this in an `omnisharp.json` file in the workspace root:
    ````json
    {
      "cake": {
        "enabled": true,
        "bakeryPath": "~/.vscode/extensions/cake-build.cake-vscode-2.0.0/Cake.Bakery/tools/Cake.Bakery.exe"
      }
    }
    ````

**Comment by lonix1** [comment]
Another things I noticed is in other issues people refer to something like this;
````
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/foo/project'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Found 1 Cake files.
````
But I don't have anything like that. There is no `CakeProjectSystem` in the log, it's as if omnisharp doesn't know about cake.

I also searched for `OmniSharp.Cake.dll` as mentioned in the [docs](https://cakebuild.net/docs/integrations/editors/vscode/intellisense#i-dont-see-any-error-message-and-still-dont-get-intellisense) but couldn't find it.

I reinstalled the c# extension without success.

**Comment by nils-a** [comment]
While *cake-vscode* provides some help in setting things up, *cake-vscode* is not responsible for providing language support (error-detection/compilation, auto-complete, F12-jump-do-definition...) for Cake. This is entirely based on [OmniSharp](https://github.com/OmniSharp/omnisharp-roslyn) (specifically OmniSharp.Cake) and [Cake Bakery](https://github.com/cake-build/bakery).

I'm closing this issue. I have added some explanation in the [discussion](https://github.com/orgs/cake-build/discussions/3929), as well as the [SO-question](https://stackoverflow.com/questions/73248344/vscode-intellisense-support-for-cake/73316770#73316770).
