### ISSUE TITLE
Allow running tasks when cake.build/.ps1 is in a subfolder

### ISSUE THREAD

**Issue by Roemer** [cake-build/cake-vscode#73]
Currently it is not possible to run cake tasks when the cake.build/.ps1 is not in the root.
This should somehow be configurable.

**Comment by gep13** [comment]
@Roemer starting to look at this extension again...

Could you provide a small sample application that I can use to replicate this problem?

**Comment by Roemer** [comment]
I don't have an example repo for this (yet) but the idea is to have:
```
root
├── build
│   ├── build.cake
│   └── build.ps1
├── docu
└── src
```
Currently, the build.cake/ps1 files needs to be directly under root. Would be great to be able to configure it to also have them in some sub-folder

**Comment by gep13** [comment]
@Roemer and when you say `Run Tasks`, can you confirm exactly what you mean?

i.e. can you give me a full set of steps to reproduce the problem, so that I don't make any assumptions?

Thanks

**Comment by Roemer** [comment]
Repro steps:
- Create an empty folder (root)
- Create a folder "build" inside that folder
- Open the root folder it in VS Code
- F1 -> Cake: Install to workspace
- Enter "build\build.cake"
- Yes/Yes/Yes
- Task -> Run Task... -> Cake: Run Default

There are multiple issues here:
1.  The build folder needs to exist, otherwise the build.cake file is silently not created
2. Only the build.cake file is in the build folder, the other files (ps1, sh, config, tools) are in the root
3. On the last step, you get an error: `C:/temp/ctest/build.cake:0: Could not find script 'C:/temp/ctest/build.cake'.

**Comment by WalkerCodeRanger** [comment]
Was this working and broke recently? I have a project where the build.cake is in a subfolder, but the build.ps1 is at the root and has been modified to point to it. It was working from and I had build tasks. I just upgraded VS Code to and now 1.25.0 it started giving "No build task to run found. Configure Build Task..." when I pick "Run Build Task..." (ctrl+shift+B). I'm running cake-build.cake-vscode 0.11.2

**Comment by gep13** [comment]
@WalkerCodeRanger looks like something has changed 😢 I have just tried the same thing, i.e. updating to latest VS Code, and when I click "Run Task" it is no longer finding the tasks that are there.

**Comment by gep13** [comment]
@WalkerCodeRanger I have raised an issue about this here: https://github.com/Microsoft/vscode/issues/53673

**Comment by gep13** [comment]
@Roemer I believe that this was corrected as a result of upstream changes.  Let me know if this is still an issue.
