### ISSUE TITLE
Can't collapse #regions

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/cake-vscode#8]
According to [this](https://github.com/cake-build/cake-vscode/blob/b58886c23bf38d7d436fedaa2261a912e8171839/syntaxes/cake.json#L7-L8), I expected `#region`s in Cake script to be collapsible, but they're not. Am I missing something? I'm using VSCode 1.0.0 and version 0.1.1 of the Cake extension.

**Comment by devlead** [comment]
Does it work for you without the addin and in an regular .cs C# file?

Code folding was added in 1.0 so it's a new feature in VSCode, could be that all cases aren't covered by the editor itself.

**Comment by thomaslevesque** [comment]
> Does it work for you without the addin and in an regular .cs C# file?

No, it doesn't. I had hoped that the folding pattern defined in cake.json would make it work anyway.

**Comment by patriksvensson** [comment]
@thomaslevesque @devlead I suspect [this](https://github.com/cake-build/cake-vscode/blob/develop/config/cake.configuration.json) is what enables collapsing of blocks in vs code.

**Comment by thomaslevesque** [comment]
> @thomaslevesque @devlead I suspect this is what enables collapsing of blocks in vs code.

Yes, probably. But what is the meaning of `foldingStartMarker` and `foldingStopMarker`, then?

**Comment by patriksvensson** [comment]
@thomaslevesque No idea. A lot of [cargo cult](https://en.wikipedia.org/wiki/Cargo_cult) in that configuration file :smile:

**Comment by gep13** [comment]
@thomaslevesque can you confirm if this is working for you or not, or whether this is still a problem?

**Comment by thomaslevesque** [comment]
@gep13 no, it still doesn't work. It's working in normal C# files.
It's not a big issue, but it would be nice if it worked ;)

**Comment by gep13** [comment]
@thomaslevesque is this something that you are interested in helping out with?

**Comment by thomaslevesque** [comment]
@gep13 to be honest, not really... I have zero experience with VSCode extensions, and I'm not really interested in learning at this time ;)

**Comment by Roemer** [comment]
I guess this is the issue which tracks the state in Visual Studio Code:
https://github.com/Microsoft/vscode/issues/3422
Unless this is solved, it seems to be hard to have correct folding.

**Comment by gep13** [comment]
@Roemer thank you for linking to that issue.  This seems like an upstream problem, so for now, unless there are any objections, I am going to go ahead and close this issue.

Please feel free to respond if there are additional comments.
