### ISSUE TITLE
Not getting "cake script" support after installing the extension

### ISSUE THREAD

**Issue by trondhindenes** [cake-build/cake-vscode#83]
On Ubuntu 17.10, cake files are showing up as "C#" type files instead of "Cake Script". Also I can't manually select "Cake script" as file type, since it's not in the list of "known" file types.

I'm running the 0.10.1of the extension.

**Comment by devlead** [comment]
Cake script highlighting is now handled by the standard C# extensions, so this is expected behavior. Intellisense is handled by Omnisharp just as with C# by installing Bakery, there's an command for this in the latest version of the Cake extension.

**Comment by trondhindenes** [comment]
okay that makes sense. However, "Format Document" doesnt work for example, even tho I have the required C# extensions/monisharp packages installed. Shouldn't this work for .cake files aswell?

**Comment by mholo65** [comment]
Yes, we currently don’t support any ”code actions” in the Cake OmniSharp plugin. This basically means we lack support for stuff like ”Format Document”, ”Rename..”, ”Add missing usings, etc...”.

**Comment by jrgcubano** [comment]
Well, I was just thinking the other day to add some of those features that you comment @trondhindenes!

**Comment by gep13** [comment]
@mholo65 am I right in saying that these features will just start to "light" up with newer releases of Cake.Bakery and Omnisharp?  I don't think that there is anything to do here for this extension is there?

**Comment by mholo65** [comment]
Rename and Roslyn code actions, such as add missing usings are available in latest omnisharp and will most probably be made available by default in VS Code with next release of the C# extension. If you want it today just add `”omnisharp.path”: ”latest”` in your workspace config and restart omnisharp server. But beware, as these are bleeding edge bits, it might not be 100% compatible with your C# extension for VS Code.

Formatting is not yet implemented, PRs are welcome :wink: I’d be happy to guide anyone that wants to take a stab at it. It *should* be quite an easy PR.

**Comment by gep13** [comment]
@trondhindenes I am going to go ahead and close this out, as this functionality will simply start appearing as other things are released.  Let me know if you have any questions.
