### ISSUE TITLE
Permission Denied when trying to Run Tasks

### ISSUE THREAD

**Issue by lganderson** [cake-build/cake-vscode#86]
When using the Tasks: Run Task command and selecting a Cake Task to run I get the following error in the Terminal window.

```
/bin/bash: ./build.sh: Permission denied
The terminal process terminated with exit code: 126
```

![screen shot 2018-02-14 at 8 48 30 am](https://user-images.githubusercontent.com/7017877/36210693-ba2dc2aa-1164-11e8-9cdb-ed7b47ae009c.png)

**Versions**:
macOS - 10.13.2
VS Code - 1.20.1
cake-vscode - 0.10.1

**Comment by patriksvensson** [comment]
Make sure that you give your `build.sh` script executable permissions.

```
> chmod +x build.sh
```

**Comment by lganderson** [comment]
That fixed the issue, thank you.
