### ISSUE TITLE
build.ps1 is empty after running the Install a bootstrapper command for Windows

### ISSUE THREAD

**Issue by MarkKharitonov** [cake-build/cake-vscode#88]
I have VS Code version 1.22.2 (installed today) and Cake plugin version 0.10.1

Running the Install a bootstrapper and choosing the Windows version generates an empty build.ps1 file.
Note, that the selecting the Linux version generates a non empty build.sh script, so this is a purely Windows issue.

**Comment by gep13** [comment]
@MarkKharitonov apologies for the lack of response on this.  I am starting to look at the extension again.

Can you please confirm if you are still seeing this issue for you?

I have just tested on a new machine, and both the PowerShell and Bash bootstrappers download successfully for me.

**Comment by gep13** [comment]
Going to close this issue due to lack of response.

**Comment by MarkKharitonov** [comment]
Sorry, lost interest.
