### ISSUE TITLE
Error message "command 'cake.intellisense' not found"

### ISSUE THREAD

**Issue by JorisMolnar** [cake-build/cake-vscode#92]
Today I received an update to the Cake extension for Visual Studio Code. 

After this update, when I run any of the Cake commands in VS Code, I get the following error message (dependent on the command):

> command 'cake.*commandname*' not found

If I open the Developer Tools of VS Code I can see the following errors in the console log:

![image](https://user-images.githubusercontent.com/20184617/42155023-8b1a155a-7de7-11e8-9acf-fa12a0e28222.png)
[VisualStudioCodeDevToolsCakeError.log](https://github.com/cake-build/cake-vscode/files/2154531/VisualStudioCodeDevToolsCakeError.log)

I've confirmed with a colleague that it was working before the new version of the cake extension got installed.

**Comment by pascalberger** [comment]
This is a known issue with the packaging of the latest version of the extension and we're currently working on a fix.

In the meantime you can try the following:

* Close Visual Studio Code
* Open Command Prompt
* Navigate to C:/Users/<your user name>/.vscode/extensions
* Navigate to the Cake extension folder for version 0.11.1
* Run `npm install`
* Re-open Visual Studio Code

**Comment by gep13** [comment]
@JorisMolnar on a side note...

Where did you find that Developer Tools for VS Code window?  I was hunting for that this morning, but I couldn't find it 😄

**Comment by JorisMolnar** [comment]
@gep13 Right here 😊

![image](https://user-images.githubusercontent.com/20184617/42156972-c3cb3032-7dec-11e8-8f51-cb6a7b5c031c.png)

**Comment by gep13** [comment]
Doh! I looked through every other menu, apart from this one!!

Thank you very much!

**Comment by gep13** [comment]
@JorisMolnar thank you very much for taking the time to post this issue.  Your original screenshot directed me to exactly the cause of the problem.  I have just pushed out a new version of the extension, 0.11.2, which should correct the problem.  Please let us know if you continue to see issues.

**Comment by Lakkanna** [comment]
check .vscodeignore make sure that it's not containing node_modules, if exists remove node_modules from .vscodeignore

**Comment by ronilaukkarinen** [comment]
@Lakkanna You are a lifesaver! I literally bashed my head to the wall 4 hours with this... published my first vscode plugin and kinda new to it, after hours of googling I finally found your answer. I don't know what node_modules was to do in .vscodeignore but I'm glad I finally got this solved. So thank you so much!
