### ISSUE TITLE
Codelens does not work if there is a space in the path

### ISSUE THREAD

**Issue by EifelMono** [cake-build/cake-vscode#94]
Codelens does not work if there is a space in the path.
This happens with macOS and Windows

I can not compile the project....?!?

ORIGINAL
```
const buildCommand =
        os.platform() === 'win32'
            ? `powershell -ExecutionPolicy ByPass -File build.ps1 -script ${fileName} -target \"${taskName}\" -verbosity=${runConfig.verbosity}`
            : `./build.sh --script ${fileName} --target=\"${taskName}\" --verbosity=${runConfig.verbosity}`;
```

FIXED
```
const buildCommand =
        os.platform() === 'win32'
            ? `powershell -ExecutionPolicy ByPass -File build.ps1 -script \"${fileName}\" -target \"${taskName}\" -verbosity ${runConfig.verbosity}`
            : `./build.sh --script=\"${fileName}\" --target=\"${taskName}\" --verbosity=${runConfig.verbosity}`;
```

**Comment by gep13** [comment]
@EifelMono thank you for taking the time to report this!  This should be corrected in the next release of the Visual Studio Code addin for Cake.

**Comment by gep13** [comment]
@EifelMono 0.11.3 has been pushed to the marketplace.  Can you please take this for a spin, and let us know if this has fixed the problem that you are seeing.

**Comment by EifelMono** [comment]
@gep13  

MAC:
Codenles does not work on a Mac because the equal char is missing between the script and the fileName
bug: ./build.sh --script \"${fileName}\" ......
fix: ./build.sh --script=\"${fileName}\" ......
If I add the equal char in the command line the path with blank works.

Windows:
On Windows it works.
FYI the verbosity switch on windows has also an equal char but it works.

**Comment by mholo65** [comment]
@gep13 @jrgcubano any reason why Code lens action is using bootstrapper when executing Cake? Wouldn't it be wise to just kick-off `cake.exe` or `dotnet cake.dll` instead?

**Comment by gep13** [comment]
@EifelMono can you please try again with 0.11.4 and let me know if you are still running into problems?  Thanks

**Comment by EifelMono** [comment]
@gep13 

Code lens "run task" now works on macOS and windows. It works also with a blank in the path.

But "debug task" does not work on macOS and Windows.
It downloads the Cake.CoreCLR starts the debugger and than ????

I have attached two videos macOS and Windows about that.

https://github.com/EifelMono/ReportedBugs/tree/master/cake-build/cake-vscode/94

**Comment by gep13** [comment]
I haven’t checked the video, but can you provide a link to the project you are trying to debug? It could be that you are using something that isn’t compatible with Cake.CoreClr which is what debugging is using by default. In this instance, you would need to modify the Cake settings to use mono as the debugger rather than .net core.

**Comment by gep13** [comment]
I will try to look at this tonight, and I will let you know what I find.
