### ISSUE TITLE
Can't get any of the commands to work in vs code

### ISSUE THREAD

**Issue by theperm** [cake-build/cake-vscode#97]
For example execute of Cake: Install a bootstrapper
results in toast message popup command 'cake.bootstrapper' not found

Similar message occurs with other commands

Uninstalled Cake extensions and reinstalled but it made no difference. 

Any ideas?

**Comment by gep13** [comment]
@theperm can you please confirm what version of the Cake extension you have installed?

**Comment by patriksvensson** [comment]
@theperm What version of the Cake extension are you using?

**Comment by theperm** [comment]
The latest that shows in VS code extensions 0.11.4

**Comment by gep13** [comment]
@theperm are you on Mac, Linux or Windows?

There was an issue with the original 0.11.0 package where the `out` folder wasn't copied into the generated vsix folder, which caused this problem, but that has been resolved.  It could be that you have a local cached version of the extension lurking around that needs to be tidied up?!?

If you let me know what OS you are running, we can dig into the extension folder and have a look.

**Comment by theperm** [comment]
I think its be working now. I saw the video there about the 10.0 issue and it looked like that si must have had that version before i reinstalled, i restarted after the re-install and the commands i have tried now work. Thanks

**Comment by gep13** [comment]
Glad to hear you got it working!
