### ISSUE TITLE
Merge Conflict Actions Missing

### ISSUE THREAD

**Issue by Roemer** [cake-build/cake-vscode#98]
With the cake extension enabled, I do not see the merge conflicts actions anymore.
See https://github.com/eamodio/vscode-gitlens/issues/344 for a similar issue in another vscode addin.
This is since cake adds its own codelens to run tasks.

**Comment by gep13** [comment]
@Roemer apologies for not coming back to you sooner about this!

Reading through that issue that you linked it would appear that the underlying issue was with VSCode, and was fixed in an update.

I am going to assume that the same is true here, and I will close out this issue.  Thanks
