### ISSUE TITLE
Add DocumentSymbolProvider for Cake Scripts to enable breadcrumb and outline functionality

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake-vscode#99]
Visual Studio Code 1.26 added [breadcrumb support](https://code.visualstudio.com/updates/v1_26#_breadcrumbs). It would be nice if for Cake files breadcrumbs for the different Tasks (and Setup / Teardown) would be shown to allow quick navigation.

**Comment by nils-a** [comment]
Population of the breadcrumb is tied to `symbols` and while adding symbols is easy, parsing of the code is not 😄 

My first test:
![image](https://user-images.githubusercontent.com/349188/99236953-21f4dc00-27f8-11eb-8372-5773d1b0a94f.png)


So I'm wondering whether we should really add our own `DocumentSymbolProvider` or if it's possible to get Cake support into OmniSharp `CodeStructureRequests`. (Which in turn would tie the usage to OmniSharp...)

**Comment by gep13** [comment]
I believe I remember speaking to @mholo65 about this, and this is something that would be better coming from OmniSharp or from the Cake LSP.

**Comment by nils-a** [comment]
... the Cake LSP .... 

The last time I tried writing one I failed miserably. (Or rather I ran out of evergy to get even the simplest of demos to work)

So, what's the status of the Cake LSP?

**Comment by mholo65** [comment]
> 
> 
> ... the Cake LSP ....
> 
> The last time I tried writing one I failed miserably. (Or rather I ran out of evergy to get even the simplest of demos to work)
> 
> So, what's the status of the Cake LSP?

I've something working, but will take some time before we can take it into use. Once that's done, we should most certainly implement these kind of feature in the language server. Having that said, if you want this now, feel free to submit a PR here, but keep in mind that it will most probably be removed once we have our own working Cake LSP server.
